services:
  postgres1:
    image: postgres:15
    container_name: postgres1
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: strongpassword123
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"
    volumes:
      - pgdata1:/var/lib/postgresql/data

  postgres2:
    image: postgres:15
    container_name: postgres2
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: strongpassword123
      POSTGRES_DB: mydatabase
    ports:
      - "5434:5432"
    volumes:
      - pgdata2:/var/lib/postgresql/data
      
  postgres3:
    image: postgres:15
    container_name: postgres3
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: strongpassword123
      POSTGRES_DB: mydatabase
    ports:
      - "5435:5432"
    volumes:
      - pgdata3:/var/lib/postgresql/data

volumes:
  pgdata1:
  pgdata2:
  pgdata3:
